### ISSUE TITLE
Tetris ROM does not run

### ISSUE THREAD

**Issue by kevlarballoons** [amhndu/SimpleNES#1]
`[Cartridge.cpp:50] Reading ROM from path: Tetris (USA).nes
[Cartridge.cpp:68] Reading header, it dictates: 
[Cartridge.cpp:71] 16KB PRG-ROM Banks: 2
[Cartridge.cpp:79] 8KB CHR-ROM Banks: 2
[Cartridge.cpp:82] Name Table Mirroring: 0
[Cartridge.cpp:85] Mapper #: 1
[Cartridge.cpp:88] Extended (CPU) RAM: false
[Cartridge.cpp:102] ROM is NTSC compatible.
[MapperSxROM.cpp:29] Using CHR-ROM
[PictureBus.cpp:94] Unsupported Name Table mirroring : 1162765676
[CPU.cpp:138] Unrecognized opcode: 2
[CPU.cpp:138] Unrecognized opcode: 2
[CPU.cpp:138] Unrecognized opcode: 42
[CPU.cpp:138] Unrecognized opcode: b2
[CPU.cpp:138] Unrecognized opcode: 5a
[CPU.cpp:138] Unrecognized opcode: 42
`
There is a gray screen in the main window.

**Comment by amhndu** [comment]
Thanks for reporting the bug!  
It has been fixed

**Comment by amhndu** [comment]
Can you confirm if this works for you ?

**Comment by kevlarballoons** [comment]
Yes, it works excellently. It's a very good emulator. I think if you added a key config menu into the window (instead of a configuration menu) that would be great, but I know that it's probably really hard. (I can't understand the source code, but that's because I only know basic C++)
