### ISSUE TITLE
i can not build this project 

### ISSUE THREAD

**Issue by wzyjobs** [amhndu/SimpleNES#10]
sorry,i can not build this project , am i wrong to use the lib that version in the image? 3q
![image](https://user-images.githubusercontent.com/38713624/93662223-34b99180-fa91-11ea-9ea9-6af6e93fb7ce.png)
![image](https://user-images.githubusercontent.com/38713624/93662236-4d29ac00-fa91-11ea-82ee-3d3a5882acd5.png)

**Comment by amhndu** [comment]
The download option looks about right, but have you installed it properly? I'm not familiar with Max OS X to comment on it. After downloading, did you install it in a system folder? Do you have cmake? Does CLion/cmake know where to find it?

**Comment by csanycall** [comment]
macOS, the same problem~
comment the line, compile ok, I'll test it with rom

**Comment by amhndu** [comment]
Can you post the error that you actually get on that line?

**Comment by ape-casear** [comment]
macOS, the same problem~

**Comment by amhndu** [comment]
Can you pull and try again? I don't have a Mac so I can't test directly but I think it should be fixed now.

**Comment by ape-casear** [comment]
```
Author: Amish Naidu <amhndu@gmail.com>
Date:   Wed Nov 11 16:53:07 2020 +0530

    Use sf::Uint32 instead of std::uint32_t
```
Already up to date.

and results
```
/Users/a123/Dpan/learn/SimpleNES/src/PPU.cpp:181:45: error: no matching
      conversion for functional-style cast from 'const sf::Uint32' (aka
      'const unsigned int') to 'sf::Color'
  ...= sf::Color(colors[m_bus.readPalette(paletteAddr)]);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Frameworks/SFML.framework/Headers/Graphics/Color.hpp:40:25: note: 
      candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'const sf::Uint32' (aka 'const unsigned int') to
      'const sf::Color' for 1st argument
class SFML_GRAPHICS_API Color
                        ^
/Library/Frameworks/SFML.framework/Headers/Graphics/Color.hpp:40:25: note: 
      candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'const sf::Uint32' (aka 'const unsigned int') to
      'sf::Color' for 1st argument
/Library/Frameworks/SFML.framework/Headers/Graphics/Color.hpp:51:5: note: 
      candidate constructor not viable: requires 0 arguments, but 1 was provided
    Color();
    ^
/Library/Frameworks/SFML.framework/Headers/Graphics/Color.hpp:62:5: note: 
      candidate constructor not viable: requires at least 3 arguments, but 1 was
      provided
    Color(Uint8 red, Uint8 green, Uint8 blue, Uint8 alpha = 255);
    ^
```

**Comment by amhndu** [comment]
I do not have a mac, so I can not reproduce the steps you've taken here. The best I could do was run it as a Github Action #13 which uses brew to install sfml and that seems to compile fine.
I highly recommend using package managers over installing things manually.
For mac, [brew](https://brew.sh/) is good!
All you need to do is run `brew install sfml`
