### ISSUE TITLE
run to crash.

### ISSUE THREAD

**Issue by arther008** [amhndu/SimpleNES#11]
My building of this project scceeds, but run to crash when the game picture starts. is it a problem because of  x64 building?

**Comment by amhndu** [comment]
What output do you see on the command line? x64 should not be a problem, it's developed using that.
Note that ROMs must USA/Japan or World versions only i.e. NTSC compatible

**Comment by zwh000** [comment]
I have the same question, and my ROMs is NTSC compatible. However, it crashed.
Is it a problem with my computer?
```Reading header, it dictates:
16KB PRG-ROM Banks: 2
8KB CHR-ROM Banks: 1
Name Table Mirroring: 1
Mapper #: 0
Extended (CPU) RAM: false
ROM is NTSC compatible.

**Comment by amhndu** [comment]
Closing because it's unclear what causes the issue.
