### ISSUE TITLE
Can I run SmileNES on my windows 10?

### ISSUE THREAD

**Issue by houko** [amhndu/SimpleNES#12]
I find the file `FindSFML.cmke`, it seems not contains windows?

**Comment by amhndu** [comment]
For windows, you'll have to set up the paths yourself I think. When you run the cmake gui, it'll not be able to find sfml, then you'll have to enter the path for sfml.

**Comment by houko** [comment]
> For windows, you'll have to set up the paths yourself I think. When you run the cmake gui, it'll not be able to find sfml, then you'll have to enter the path for sfml.

thank you for your reply. I will try it later..
