### ISSUE TITLE
No sound？

### ISSUE THREAD

**Issue by nikissXI** [amhndu/SimpleNES#15]
I am so excited that I build your project successfully!
But, why the game no sound?

**Comment by amhndu** [comment]
I have unfortunately not implemented it yet, I had started implementing it, but had some issues due the library as well as had little time at the time, so couldn't finish it. I've considered going back and finally finishing it, but using SFML for realtime audio generation is a little difficult. It's been a few years and I have moved on from the project unfortunately.
