### ISSUE TITLE
line 152 at KeybindingsParser.cpp

### ISSUE THREAD

**Issue by sora-blue** [amhndu/SimpleNES#17]
it should be as follows:
` if (line.empty() || line[0] == '#' )`
the original is:
` if (line[0] == '#' || line.empty())`
if line has nothing, operator || will deal with the fr operand which may be out-of-range

**Comment by wanzzhehe** [comment]
a detail

**Comment by amhndu** [comment]
Sorry about the late response, but thanks for reaching out!

Your line is reasoning is correct, in this case, `line.empty()` should be first to avoid out-of-range, but unlike other containers,`std::string` is always guaranteed to be null-terminated. Thus, even if it's empty, it has one character, `'\0'`!
