### ISSUE TITLE
Update for better thread, type, etc. safety and performance

### ISSUE THREAD

**Issue by WSLUser** [amhndu/SimpleNES#18]
Make use of https://github.com/pinam45/dynamic_bitset and it's optional dependency: https://github.com/kimwalisch/libpopcnt

Also make use of https://github.com/fmtlib/fmt, which is part of the C++ 20 standard but available for earlier versions.

Potentially make use of https://github.com/martinus/robin-hood-hashing for maps. 

Add into the build step to use https://github.com/microsoft/mimalloc to greatly improve performance of allocations.

**Comment by amhndu** [comment]
Given the poor support of package management in C++ and given that these don't really *add* anything to the project, other than change for the sake of it, I'm afraid I don't really see the positive here.

**Comment by WSLUser** [comment]
> Given the poor support of package management in C++

Git submodules work just fine in C++ as any other language.  This are mostly header libraries to include and replace parts of the code with.  Improving type-safety, thread-safety, etc. in addition to boosting performance hardly seems to be adding nothing to the project. Code health is important and ensures less bugs, less resource issues for users and helps prevent crashes. All of these are worth-while endeavors.
