### ISSUE TITLE
make -j4  error

### ISSUE THREAD

**Issue by zhicai-dev** [amhndu/SimpleNES#19]
when make -j4  error，why？

**Comment by lalalalini** [comment]
ei,i have same problem ,so why?

**Comment by lalalalini** [comment]
> 

but it says configuring done, emmm,if i use MS to configure,it would appears many errors,but using GNU it success,oh,I feel dizzy

**Comment by amhndu** [comment]
You have to use the right compiled library. See https://www.sfml-dev.org/download/sfml/2.5.1/ there are different versions provided, it has to match.

**Comment by lalalalini** [comment]
> 
oh no again,when Generating,it always says
"CMake Error at CMakeLists.txt:74 (add_executable):
  No SOURCES given to target: SimpleNES"

how can i solve it.(cry)
i use windows10, vs2019,visual C++2015-2019 ,cmake3.23.0 and my SFML is Visual C++ 15 (2017) - 64-bit,do i get wrong?
