### ISSUE TITLE
Mapper 4

### ISSUE THREAD

**Issue by amhndu** [amhndu/SimpleNES#23]

**Comment by SuzieQQ** [comment]
> _No description provided._

mapper 4 has some reading problems with a few days example batman returs

and scanline problems to solve
that's why some games either don't start or don't go into play
super mario example 2
and final fantasy III

**Comment by SuzieQQ** [comment]
![FF3-2](https://user-images.githubusercontent.com/44621050/155453186-4ef9cb1f-5374-468e-b55a-362622a6e374.png)
 
![FF3](https://user-images.githubusercontent.com/44621050/155453227-c0476d77-2fca-46f3-af8c-50948133468a.png)

i am testing and i think i have problems with RAM
if I insert it in the readCHR and writeCHR I can get final fantasy 3 playable

**Comment by amhndu** [comment]
Hey, I've refactored mapper 4 and along with it fixed some bugs. It never crashes now. However there are still some visual artefacts, which could either be an issue with the PPU or the mapper, I'm not sure.

**Comment by SuzieQQ** [comment]
I didn't have much time yesterday, I tried various games for mapper 4 and they don't work anymore, maybe it's the mapper

**Comment by amhndu** [comment]
Can you tell me what games you've tried?

**Comment by SuzieQQ** [comment]
> Can you tell me what games you've tried?

Bonks, super Mario 3 , alien 3 

Super Mario 3 graphic glitches and crashes ! It got worse it did not have those glitches ,
Alien 3 used to go up to the menu now not anymore ,
Bonks goes in game but has glitches before it was playable

**Comment by amhndu** [comment]
Super Mario 3 and Kirby's Adventure should work now. Some other games should also have small improvements.
There are still still some flickering in SMB3 title screen and Kirby's Adventure status bar, but that'll need even better timing fixes. I'll try to refactor the MMC3 counter at some point to improve performance as I think SMB3 is a little slow in debug mode.
@SuzieQQ @grimoire

**Comment by SuzieQQ** [comment]
![Schermata a 2022-08-22 05-22-01](https://user-images.githubusercontent.c
![Schermata a 2022-08-22 05-29-32](https://user-images.githubusercontent.com/44621050/185833522-7aabf4d6-f37d-46e6-873d-4543d74636a8.png)
om/44621050/185833494-e9330d9b-2c95-4aad-8908-ff58fd0e3842.png)
![Schermata a 2022-08-22 05-25-23](https://user-images.githubusercontent.com/44621050/185833503-127ecfd9-6f09-4188-ab34-df0fabc4546d.png)

with the latest fix was also fixed super mario 2 , final fantasy, and a tmn game , great job guys
