### ISSUE TITLE
[Cartridge.cpp:45] Could not open ROM file from path: /home/Shunkang/Games/SuperMarioBros.nes

### ISSUE THREAD

**Issue by 878547387** [amhndu/SimpleNES#25]
Shunkang@XiaomiPro14:~/Konrad/code/SimpleNES/build$ ./SimpleNES ~/Games/SuperMarioBros.nes
[Cartridge.cpp:45] Could not open ROM file from path: /home/Shunkang/Games/SuperMarioBros.nes

**Comment by amhndu** [comment]
@878547387 Is the file path and permissions correct?
