### ISSUE TITLE
Could NOT find SFML missing LIBRARY

### ISSUE THREAD

**Issue by lalalalini** [amhndu/SimpleNES#26]
i run it in windows system ,but i got a error about:
CMake Error at cmake/Modules/FindSFML.cmake:358 (message):
Could NOT find SFML (missing: SFML_AUDIO_LIBRARY SFML_GRAPHICS_LIBRARY
 SFML_WINDOW_LIBRARY SFML_SYSTEM_LIBRARY)	
  
i don't how to solve it,can someboby get me help(cry),

**Comment by amhndu** [comment]
Based on your IDE, check https://www.sfml-dev.org/tutorials/2.5/start-vc.php or https://www.sfml-dev.org/tutorials/2.5/start-cb.php

**Comment by lalalalini** [comment]
> Based on your IDE, check https://www.sfml-dev.org/tutorials/2.5/start-vc.php or https://www.sfml-dev.org/tutorials/2.5/start-cb.php

yeah!!!!!!!! i got it !!! I added an extra ’sfml_static‘in Debug,but not added in Relese,now i delete it,it work! lol,thank u!
