### ISSUE TITLE
how to build on windows?

### ISSUE THREAD

**Issue by youkechat** [amhndu/SimpleNES#31]

**Comment by amhndu** [comment]
You need to download sfml, cmake and any build tooling (like Visual Studio or Visual Studio Code).
Please see sfml tutorials on more help

**Comment by youkechat** [comment]
ok thanks

**Comment by youkechat** [comment]
vs2019 compile error 
D:\code\cpp\SimpleNES\src\Mapper11.cpp(58): error C4716: 'sn::Mapper11::getPagePtr': must return a value

**Comment by youkechat** [comment]
after add return nullptr, compiled successed, but when run games, everythins works well except doesn't have any sound,  FYI:SimpleNES built with shared library, and copy SMFL exlibs from libs-msvc direcotry.

use you provided executable binary dosen't have this problem

**Comment by youkechat** [comment]
@amhndu cc?

**Comment by amhndu** [comment]
There is no sound functionality yet. Unfortunately I haven't had the time to implement it

**Comment by youkechat** [comment]
ok  thanks
