### ISSUE TITLE
Keyboard Issue running on an M1 mac 

### ISSUE THREAD

**Issue by MrPolymorph** [amhndu/SimpleNES#37]
After building and running the basic nestes.nes file, the output from the terminal was:

We got a keyboard without any keys

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1191258/229310409-ce268fb3-a9f1-4312-8a6d-2c8166373628.png">

**Comment by ldesuque** [comment]
Just change the input monitoring :

![Capture d’écran 2023-04-03 à 20 55 25](https://user-images.githubusercontent.com/4763480/229601343-e5a5141d-b212-474e-8269-4a6142ce4aff.png)

**Comment by MrPolymorph** [comment]
Oh awesome, I didn't know that was a thing! 

Thanks!
