### ISSUE TITLE
opcode match

### ISSUE THREAD

**Issue by narakai** [amhndu/SimpleNES#41]
Hi, 

In CPUOpcodes.h, I found there are opcodes and respective hex number in enum OperationImplied, but other enums like Operation1, Operation2..., there are only opcodes defined, no hex number at all. So I am wondering why we can still use opcodes(should be a hex number) in 'Switch-Case' to match the codes in  these enum?

Say enum Operation1
{
    ORA, /* there's no hex like ORA = E9 defined ?*/
    AND,
    EOR,
    ADC,
    STA,
    LDA,
    CMP,
    SBC,
};

In CPU.cc:

switch (op){
    case ORA:
    // do some stuff
     break;
}

**Comment by amhndu** [comment]
In the opcode, operation is represented by the highest 3 bits. Thus if you mask the opcode by 11100000b (0xE0) and shift by 5, you get the operation which is a number from 0 to 7. The enum value is just this number.

See constants [OperationMask and OperationShift]( https://github.com/amhndu/SimpleNES/blob/master/include/CPUOpcodes.h#L8) and [example decode logic](https://github.com/amhndu/SimpleNES/blob/master/src/CPU.cpp#L369).

Reference: https://llx.com/Neil/a2/opcodes.html

**Comment by narakai** [comment]
Thanks for the reply, it helps a lot!
