### ISSUE TITLE
where to put keybindings.conf

### ISSUE THREAD

**Issue by wangxiaoyan369** [amhndu/SimpleNES#47]

**Comment by amhndu** [comment]
Same directory as the executable

**Comment by wangxiaoyan369** [comment]
Can it be passed through command line arguments?

**Comment by amhndu** [comment]
Unfortunately no, currently it's fixed. Feel free to make a PR

**Comment by wanzzhehe** [comment]
I just push a simple PR.
________________________________
发件人: Amish Kumar Naidu ***@***.***>
发送时间: 2024年6月4日 18:34
收件人: amhndu/SimpleNES ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [amhndu/SimpleNES] where to put keybindings.conf (Issue #47)


Unfortunately no, currently it's fixed. Feel free to make a PR

―
