### ISSUE TITLE
Compile Error in MacOS

### ISSUE THREAD

**Issue by Lewin671** [amhndu/SimpleNES#5]
Threre are build logs as following:
CMake Error at cmake/Modules/FindSFML.cmake:358 (message):
  Could NOT find SFML (missing: SFML_AUDIO_LIBRARY SFML_GRAPHICS_LIBRARY
  SFML_WINDOW_LIBRARY SFML_SYSTEM_LIBRARY)
Call Stack (most recent call first):
  CMakeLists.txt:63 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by amhndu** [comment]
You need to install SFML to compile it

**Comment by Lewin671** [comment]
> You need to install SFML to compile it

Thank you! I have solved it.
