### ISSUE TITLE
Incorrect address ranges in picturebus read and write

### ISSUE THREAD

**Issue by monkeysoop** [amhndu/SimpleNES#50]
The ppu address space is divided into chr rom: 0x0000 - 0x1FFF, vram: 0x2000 - 0x3EFF, palette: 0x3F00 - 0x3FFF, so 

this is good:
if (addr < 0x2000)
{
         m_mapper->writeCHR(addr, value);
} 

but these:
else if (addr < 0x3eff)
{
         ...
}

else if (addr < 0x3fff)
{
         ...
}
are incorrect, because they don't include the last possible address, for example for a vram read from 0x3EFF would miss the correct branch and result in a palette read, for address 0x3FFF it would just return 0

in other emulators they either use < 0x3F00 and < 0x4000 or <= 0x3EFF and <= 0x3FFF

**Comment by amhndu** [comment]
Good catch! It'll be a while before I can get to it, PRs welcome!

**Comment by amhndu** [comment]
Fixed in #51
