### ISSUE TITLE
$ ./SimpleNES ~/Games/SuperMarioBros.nes

### ISSUE THREAD

**Issue by bu6eryutang** [amhndu/SimpleNES#7]
Why does "could not open ROM file from path bueryt/Games/SuperMarioBros.nes" appear when executing the title, thanks.

**Comment by cheepmunc** [comment]
你需要下载一个.nes镜像，可以从这里下载 https://romsmania.cc/roms/nintendo/super-mario-bros-242404

**Comment by amhndu** [comment]
Note that Only USA/Europe versions of the .nes files are supported, like the above.
